# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Calculator": "00_calculator.ipynb"}

modules = ["calculator.py"]

doc_url = "https://deep-diver.github.io/nbdev_test2/"

git_url = "https://github.com/deep-diver/nbdev_test2/tree/master/"

def custom_doc_links(name): return None
